actions:
    1:
        action: delete_indices
        description: "Delete old logstash indices."
        options:
            ignore_empty_list: True
            continue_if_exception: True
            disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: logstash-
          exclude: 
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 1
          exclude:
    2:
        action: delete_indices
        description: "Delete old topbeat indices."
        options:
            ignore_empty_list: True
            continue_if_exception: True
            disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: topbeat-
          exclude: 
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 1
          exclude:

